### ISSUE TITLE
Port to another editor

### ISSUE THREAD

**Issue by Alexey-T** [gh640/SublimeUnicodeSwitcher#5]
Hi
Maybe it's easy to port to CudaText editor?

**Comment by gh640** [comment]
Hi,

Yes, I believe so if CudaText editor supports a similar APIs to Sublime Text's. Though, I don't know of the editor well.

**Comment by Alexey-T** [comment]
Ok; don’t you want to port it? API doc is in wiki, menu Help/Wiki.

**Comment by gh640** [comment]
It may be a fun.

I tried checking the wiki to give it a try and found the following description.

> On macOS you must install Python 3.x, from official site python.org. Versions 3.6...3.9 are ok. CudaText will find Python then.
> 
> Python installed from Homebrew cannot be used by CudaText: it misses 32-bit .dylib file.

http://wiki.freepascal.org/CudaText#Python_on_macOS

Unfortunately my dev environment is only MacOS and I depend on Homebrew at the moment. So it can take much time for me to prepare an environment for plugin development for the editor. I don't feel like spending my time for that for now.

When I have more time and am interested more, I'll give it a try! Thank you for letting me know the editor.

**Comment by Alexey-T** [comment]
Is it right- plugin just reads selection blocks, and makes
 
    text= unicodedata.normalize('NFC', text)

for them? if yes, its super easy to make plugin for CudaText.

**Comment by Alexey-T** [comment]
I will add it to Encode plugin. don't worry.

**Comment by gh640** [comment]
> Is it right- plugin just reads selection blocks, and makes
> 
> ```
> text= unicodedata.normalize('NFC', text)
> ```
> 
> for them?

Yes, exactly. Sorry not to be able to help.
